web-standards-ru/dictionary

Names.md

@pepelsbey, странно что ты его сам не добавил :wink:

Добавил Брюса Лоусона

---

Dictionary.md

Предложено по результатам [обсуждения](https://github.com/web-standards-ru/dictionary/commit/10018a4d6fd3dbb39153b595ddb83eacb667cca8).

Вариант перевода видов селекторов

---

Dictionary.md

Добавил свойства фона

---

names.md

Обсуждение могло бы быть в #197, а пока PR с вариантом, который нравится лично мне.

Добавил Брендана Айка

---

names.md

Произношение из https://youtu.be/S4cvuuq3OKY?t=32s

Добавил Кайла Симсона

---

names.md

Добавил Пола Айриша. Произношение взял из https://www.youtube.com/watch?t=1&v=2Ih0HDFrSuM

Добавил Пола Айриша

---

names.md

Добавил И́ре Аде́ринокун

---

names.md

Самый популярный, вроде бы, вариант транскрипции по результатам обсуждения #218. И чуть поправил алфавитный порядок заодно.

Добавил Эстель Вайл

---

names.md

Ну нету ведь в ней буквы "h"... :)

Предлагаю добавить Сару Дрэснер в список

---

names.md

Привет!
Изменения отражены в названии пул реквеста. Ещё якори в меню поправил.
У меня дополнительно есть парочка предложений. Если редакторы одобрят, то закину ещё несколько коммитов в этот PR:
1. Привести имена к какому-то общему виду, в духе «Имя Фамилия» или «Фамилия Имя», чтобы однозначно было понятно, где имя, а где фамилия. Я из-за того, что они написаны по-разному, долго не мог понять, ошибка ли с Юной или нет, и почему это Брендан Айк на букву «Б». Они может быть из-за этого будут чуть непривычно звучать, зато будет понятнее.
2. Отсортировать в каждом подразделе фамилии в алфавитном порядке. Так как-то приятнее, ну и порядок всё же.
3. Это уже не совсем к теме этого PR, но: в [CONTRIBUTING.md](https://github.com/web-standards-ru/dictionary/blob/master/CONTRIBUTING.md) PR по-русски …

Добавил Матиаса Байненса, переместил Юну

---

dictionary.md

Смотри ишью https://github.com/web-standards-ru/dictionary/issues/221

Добавил корректировку font-weight: bold

---

names.md

https://vimeo.com/194815985
На второй минуте она говорит своё полное имя, а затем его сокращённый вариант, который звучит как Ирé.

Ирé, а не И́ре

---

names.md

и закрывает #257, #260 и #272 соответственно

добавляет Флорана Вершельда, Акселя Раушмайера и Венсана де Оливейру

---

names.md

@GreLI @SelenIT @jucke, согласны?

Добавляет Хуэй Цзина

---

names.md

Такой ПР подходит или лучше каждую фамилию в отдельный ПР оформлять?
Есть ли замечания по фамилиям?

Добавляет Бена Фрейна, Брэда Фроста, Реми Шарпа и Тима Кадлека

---

names.md

Заметил, что нет ещё двух довольно известных чуваков :) Обещаю, что скоро ко-во ПР-ов от меня уменьшится ))

Джейк, Пол и якорь

---

names.md

По мотивам https://soundcloud.com/web-standards/episode-32

Поправить имя «Лия»

---

names.md

Добавлен Tab Atkins

---

names.md

Предлагаю добавить в словарь разработчика Tania Rascia.

Добавить Tania Rascia

---

names.md

Добавить Давида Барона (L. David Baron)

---

names.md

Я не нашёл, что значит "W.", и не понятно, нужно ли оно в нашем словаре.
Closes #418

Добавляет Comeau Josh

---

names.md

Произношение имени объясняется в блоге на странице [About Me](https://www.industrialempathy.com/about/), также можно послушать [в начале доклада](https://youtu.be/XyVQfqmx2CI?t=27).

Добавляет Малте Убла

---

font-weights.md

Исправляет опечатку в разделе "Имена насыщенности шрифта"

---

CONTRIBUTING.md
README.md
dictionary.md
names.md

По договорённости с @pepelsbey добавляю упоминание Доки в описание проекта. Посмотрите, пожалуйста, что это ОК по формату и подаче.

Добавляет упоминание Доки

---

names.md

Предлагаю добавить автора прекрасных статей Ахмада Шадида
Написание на английском можно проверить в профиле на гитхабе - https://github.com/shadeed
Произношение можно послушать - https://youtu.be/y7g2OLVKLCM?si=AtRzGGTeFGZRCXmW&t=73
больше вариантов с произношением мне не удалось найти

Добавляет автора статей
